In [16]:
import numpy as np

# Example matrix
matrix_size = 100
A = np.random.rand(matrix_size, matrix_size)


In [19]:
def similarity(u, v):
    dot_product_uv = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    
    similarity_uv = dot_product_uv / (norm_u * norm_v)
    return similarity_uv

def kernel_matrix(data):
    n = len(data)
    K = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            K[i, j] = similarity(data[i], data[j])
    return K

def select_eigenvectors(eigenvalues, eigenvectors):
    selected_eigenvalues = []
    selected_eigenvectors = []

    for eigenvalue, eigenvector in zip(eigenvalues, eigenvectors.T):
        prob = eigenvalue / (eigenvalue + 1)
        if np.random.rand() < prob:
            selected_eigenvalues.append(eigenvalue)
            selected_eigenvectors.append(eigenvector)
    
    return np.array(selected_eigenvalues), np.array(selected_eigenvectors).T


def select_items(eigenvectors, items):
    subset_Y = []

    for eigenvector in eigenvectors.T:
        # Calculate squared magnitude of components
        squared_magnitude = np.square(np.abs(eigenvector))

        # Normalize squared magnitudes to probabilities
        probabilities = squared_magnitude / np.sum(squared_magnitude)

        # Select an item based on probabilities
        selected_index = np.random.choice(len(eigenvector), p=probabilities)
        selected_item = items[selected_index]
        subset_Y.append(selected_item)
    
    return subset_Y

def probability_of_selection(K, Y):
    # Extract submatrix Ky
    Ky = K[Y][:, Y]
    
    # Compute determinants
    det_Ky = np.linalg.det(Ky)
    det_K_plus_I = np.linalg.det(K + np.eye(K.shape[0]))  # Adding identity matrix
    
    # Compute probability of selection
    probability = det_Ky / det_K_plus_I
    
    return probability


In [20]:
K = kernel_matrix(A)
eigenvalues, eigenvectors = np.linalg.eig(K)
selected_val, selected_vec = select_eigenvectors(eigenvalues, eigenvectors)
final_vecs = select_items(selected_vec)


[array([-0.10119966,  0.04764335, -0.01675775,  0.03043598,  0.04270756,
        -0.01059905, -0.00869511,  0.06374987, -0.14766818,  0.12702979,
        -0.14787882,  0.18693363,  0.11788976,  0.17682238,  0.01530004,
        -0.02312163]),
 array([-0.09639277,  0.23703909, -0.25844059, -0.07433563,  0.02626951,
         0.0868513 , -0.03385396,  0.07299953, -0.07503579,  0.10810952,
         0.01611947, -0.02924643,  0.04176362,  0.1161142 ,  0.10216367,
        -0.14052305]),
 array([-0.09946827, -0.11921655,  0.21431509,  0.01916777, -0.06285888,
        -0.06369732,  0.03677222, -0.00707251, -0.04871684, -0.11628307,
         0.05518569, -0.06121323, -0.07564903, -0.08793273,  0.02403908,
         0.0157797 ]),
 array([-0.10061271, -0.1203286 , -0.07898421, -0.09126813,  0.0516055 ,
        -0.04933949,  0.07895369, -0.03857415, -0.04562289,  0.01196548,
         0.01027795, -0.00983606, -0.08142751,  0.17287675,  0.12722317,
        -0.20775806]),
 array([-0.10157696,  0.04199497

In [22]:
len(final_vecs)

16